language: java
jdk:
- oraclejdk8

services:
  - docker

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

notifications:
  hipchat:
    rooms:
      secure: ZMOMlKEegYI13J+QK0nl2OlKwJM0K3sT9e+/YiHxKLGtsLYpZQyYS7/8ftGhOIG1dvXhxU05ZWnDHeCWvVYSLU4FI2oH3gztT8vdxJIE1M8e6TaJEcRpidMf8TbI5N1u6z/BZKJol3d2JuwSjnl3gVuvo4E4WzAgr2VY5pBk8BCv1UnWNhqE2GjdKknXc7O4KvjY0zU+t6LPxV1kAAlnMm7WxoD9Qord7W/F+IOTmcG3vwVIix6T6ANqFxlUixwVS/ocosG7uyQvt6aNxFgaO2t/lfmHXbKEHw2vX2ijldzWlPEQ5orofCxi5cuqzTBBqXolxbjbs8mtePbJA2LsqTOgA0N6J5JFHDZa55pWJnf4W06Cr+BJKpWWPWo2e1Yp81QHYd1psCphXuPrqiyVCMvHaGIA3l4uLiqhXMWq9J/4NL+DW3No6UbsSEI8zjquJJEzRXypZBepir3P2xciBQFz5BHq1athrzUqsU3AnxJRVQ4TlF5814Dtn+DAcAo8eQ+8cQFqd7BdHKUMOF41FsZaLTVIKuZ4D+/a3GAGiZsDP9jxF6wfdXMY7mIVhH4fOiYyuQogh/WfRoKxaspISCB1wLuObfH642ocQK2f8nZLLFt3sgJuuAzGFKL1IE6fe3omMzJAN+I68u9mmOL0uX8jSLfb/npq4r0Ob5y95Z4=
